# Copyright 2022 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CE GitHub Actions TDE Classes build.
# ---------------------------------------------------------------------------

name: TDE Classes

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - gh-pages
    - p4-integ*
    - last-p4-*
  pull_request:
    types:
      - opened
      - committed
    branches:
    - '*'

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        stage:
         - stage1
         - stage2
         - stage3
         - stage4
         - stage5
         - stage6
         - stage7
         - stage8
         - stage9
         - stage10
         - stage11
         - stage12
         - stage13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Print Maven & Java version
      run: mvn -version

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

      # First run a simple compile without tests
    - name: Build
      shell: bash
      env:
        MAVEN_USER: ${{ secrets.MavenUser }}
        MAVEN_PASSWORD: ${{ secrets.MavenPassword }}
      run: |
        export DEV_ROOT=$(pwd)
        mvn --file prj/pom.xml --batch-mode -e -s .github/maven/settings.xml -U -P-modules,tde.classes -DskipTests clean install
        mvn --file prj/pom.xml --batch-mode -e -s .github/maven/settings.xml -Pmodules,-coherence,tde.classes -nsu -DskipTests clean install

      # If the build job runs successfully then run the verify stages in parallel
    - name: Verify
      timeout-minutes: 180
      shell: bash
      env:
        MAVEN_USER: ${{ secrets.MavenUser }}
        MAVEN_PASSWORD: ${{ secrets.MavenPassword }}
      run: |
        echo "Running verify ${{ matrix.stage }}"
        export DEV_ROOT=$(pwd)
        mvn --file prj/pom.xml --batch-mode -e -s .github/maven/settings.xml -P-modules,${{ matrix.stage }},-javadoc,tde.classes -Doptional -Dcoherence.SkipLargeMemoryTests=true clean verify
        mvn --file prj/pom.xml --batch-mode -e -s .github/maven/settings.xml -Pmodules,-coherence,${{ matrix.stage }},-javadoc,tde.classes -nsu -Doptional -Dcoherence.SkipLargeMemoryTests=true clean verify

    # Upload build artifacts for diagnosing failures
    - name: Build Artifacts test logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-output
        path: prj/examples/**/target/test-output/**/*
        if-no-files-found: ignore

    - name: Build Artifacts test reports
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: failsafe-surefire-test-reports
        path: prj/examples/**/target/*-reports/**/*
        if-no-files-found: ignore
