# Copyright 2020, 2025, Oracle Corporation and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CE GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: Stage 11 CI Pipeline

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  push:
    branches-ignore:
    - gh-pages
    - p4-integ*
    - last-p4-*

jobs:
  build:
    name: Parallel Build - Linux
    uses: ./.github/workflows/build-11.yaml
    secrets: inherit
    with:
      runner: windows-latest
